### ISSUE TITLE
Details about Maniskill model configs 

### ISSUE THREAD

**Issue by shen-hhao** [haosulab/ManiSkill-Legacy#11]
I wanted to test my model on some unseened environments, so I modified config files like /ManiSkill/mani_skill/assets/config_files/cabinet_models_door.yml to change the scale of the cabinet or the position and initial_qpos of the chair.
The parameters of scale seem to be unique to different types of cabinet, and the initial_qpos and position of chair seem to be randomly generated. However, if I change these parameters, the cabinet may be too large or too small for the robot to operate, and the chair may bounce up as the environment is created. So I want to ask whether there are some restrictions on the parameters in the models' config files?

Besides, I want to know can we design another reward function in _no external annotation_ challenge track?

**Comment by tongzhoumu** [comment]
Hi @shen-hhao ,

> So I want to ask whether there are some restrictions on the parameters in the models' config files?

The scales and initial poses of the objects in ManiSkill are carefully tuned case by case. It is not recommended to modify these parameters on your own because it can be tricky. 

If you want to test your model on unseen environments, perhaps you can try to make a custom train-validation split according to [this example](https://github.com/haosulab/ManiSkill#custom-split). 

> Besides, I want to know can we design another reward function in no external annotation challenge track?

It is allowed. But it is NOT allowed if you manually annotated any parts of the objects in order to design new rewards.
