### ISSUE TITLE
Question about loading a new type of robot into the environment

### ISSUE THREAD

**Issue by wkwan7** [haosulab/ManiSkill-Legacy#13]
Hi! I want to set a new type of robot as an agent in the environment for some experiments. I have got the robot's urdf file but I don't know which files I need to add and modify. Can you give me some advices?

**Comment by tongzhoumu** [comment]
Hi @Wanwk ,

It is not recommended to replace the robots since the initial states and dense reward functions of our tasks are designed for the specific robots.

However, if you really want to use a new robot, **at least** you will need to modify the following files:

- Add the robot urdf file to `mani_skill/assets/robot`
- Write a class for your new robot like [this](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/agent/agent.py#L482-L534)
- Add a robot config file like [this](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/assets/config_files/robots/mobile_a2_single_arm.yml)
- Modify the task config file like [this](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/assets/config_files/push_chair.yml#L47-L57) (Or other tasks you want to work on)
